# The first /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x09 represents the file that contains indexes, teh next /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x09
# represents the output prefix for slot value generation the last /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x09.out is the general log out put of the process
sbt -mem 5000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x00 /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x00' > /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x00.out 2>&1 &
sbt -mem 5000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x01 /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x01' > /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x01.out 2>&1 &
sbt -mem 5000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x02 /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x02' > /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x02.out 2>&1 &
sbt -mem 5000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x03 /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x03' > /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x03.out 2>&1 &
sbt -mem 5000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x04 /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x04' > /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x04.out 2>&1 &
sbt -mem 5000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x05 /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x05' > /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x05.out 2>&1 &
sbt -mem 5000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x06 /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x06' > /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x06.out 2>&1 &
sbt -mem 5000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x07 /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x07' > /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x07.out 2>&1 &
sbt -mem 5000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x08 /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x08' > /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x08.out 2>&1 &
sbt -mem 5000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x09 /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x09' > /media/sde/luceneSubmission/splittedEntityIndex/10000perentity/x09.out 2>&1 &

