sbt -mem 45000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x00 /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x00' > /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x00.out 2>&1 &
sbt -mem 45000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x01 /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x01' > /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x01.out 2>&1 &
sbt -mem 45000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x02 /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x02' > /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x02.out 2>&1 &
sbt -mem 45000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x03 /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x03' > /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x03.out 2>&1 &
sbt -mem 45000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x04 /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x04' > /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x04.out 2>&1 &
sbt -mem 45000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x05 /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x05' > /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x05.out 2>&1 &
sbt -mem 45000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x06 /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x06' > /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x06.out 2>&1 &
sbt -mem 45000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x07 /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x07' > /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x07.out 2>&1 &
sbt -mem 45000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x08 /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x08' > /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x08.out 2>&1 &
sbt -mem 45000 'run-main edu.ufl.cise.pipeline.Pipeline /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x09 /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x09' > /media/sde/luceneSubmission/splittedEntityIndex/outliersRemovedIndex/x09.out 2>&1 &

