package edu.ufl.cise;

import java.io.File;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;

/**
 * After each partial run (pause) you need to copy the log fiels generated at {@link #LOG_DIR} to
 * {@link #LOG_DIR_ARCHIVE} to make sure they are not over written and are read so that the files
 * that are already processed are skipped.
 * 
 * @author morteza
 * 
 */
public class SETTINGS {

	// Is this running on server or locally?
	public final static boolean			localRun									= isLocalRun();

	// Corpus directory on server/local
	public final static String			CORPUS_DIR_SERVER_SDE			= "/media/sde/s3.amazonaws.com/aws-publicdatasets/trec/kba/kba-streamcorpus-2013-v0_2_0-english-and-unknown-language/";
	public final static String			CORPUS_DIR_SERVER_SDD			= "/media/sdd/s3.amazonaws.com/aws-publicdatasets/trec/kba/kba-streamcorpus-2013-v0_2_0-english-and-unknown-language/";
	public final static String			CORPUS_DIR_LOCAL					= "/home/morteza/2013Corpus/s3.amazonaws.com/aws-publicdatasets/trec/kba/kba-streamcorpus-2013-v0_2_0-english-and-unknown-language/";

	// Where to store log files?
	private final static String			LOG_DIR_SERVER						= "/media/sde/runs/";
	private final static String			LOG_DIR_LOCAL							= "/home/morteza/trec/runs/";

	/**
	 * Where to store log files.
	 */
	public final static String			LOG_DIR										= (localRun) ? LOG_DIR_LOCAL : LOG_DIR_SERVER;

	// Where to read archived log files from previous runs from? To see which ones we have already
	// processed and avoid rerunning them, used as pause/resume feature ot skip some files.
	private final static String			LOG_DIR_SERVER_Archive		= "/media/sde/backupFinal/";
	private final static String			LOG_DIR_LOCAL_Archive			= "/home/morteza/trec/backup/";

	/**
	 * Archived log directory, storing the list of already processed files. Used to determine how far
	 * we have processed used as pause resume.
	 */
	public final static String			LOG_DIR_ARCHIVE						= (localRun) ? LOG_DIR_LOCAL_Archive
																																: LOG_DIR_SERVER_Archive;

	// settings to load the list of files that we need to process. Generated by the C script.
	private final static String			LOG_DIR_LOCAL_TO_PROCESS	= "/home/morteza/trec/toProcess/";
	private final static String			LOG_DIR_SERVER_TO_PROCESS	= "/media/sde/toProcess/";
	public final static String			LOG_DIR_TO_PROCESS				= (localRun) ? LOG_DIR_LOCAL_TO_PROCESS
																																: LOG_DIR_SERVER_TO_PROCESS;

	// To filter special file types containing keywords
	public static final String			FILTER										= "";

	public static final DateFormat	format										= new SimpleDateFormat("yyyy-MM-dd-HH");
	public static final DateFormat	logTimeFormat							= new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");

	// Two digit date format for proper 0-padding of day-month numbers used for file names
	DecimalFormat										numberFormatter						= new DecimalFormat("00");

	/**
	 * Are we running on a local PC or the server? to setup proper addresssing.
	 * 
	 * @return
	 */
	private static boolean isLocalRun() {
		File f = new File(CORPUS_DIR_LOCAL);
		return f.exists();
	}

	/**
	 * Default constructor that throws exception.
	 * 
	 * @throws Exception
	 */
	public SETTINGS() throws Exception {
	}
}
