/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "streamcorpus_constants.h"

namespace streamcorpus {

const streamcorpusConstants g_streamcorpus_constants;

streamcorpusConstants::streamcorpusConstants() {
}

} // namespace

