package edu.ufl.cise

case class KBAOutput (triple:Triple){
	
}

case class Row(triple:Triple) {
	
	val team_id = ""; // first column: team_id
	val system_id ="" // second column: system_id
	val doc_id ="" //third column: stream_id in the kba-stream-corpus-2013
	val topic_id = "" + triple.entity0 // fourth column: urlname of the entity
	val confidence = 0 // fifth column: confidence ∈ (0, 1000] and confidence ∈ 𝐙
	val relevance = -2 // sixth column: ccr relevance rating level integer in [-1, 0, 1, 2]
	val mention = -1 // seventh column: contains mention integer in [0, 1]
	val date_hour = "0000-00-00" // eighth column: date-hour string corresponds to the directory name, e.g. '2012-04-04-04'
	val slot_name = "" + triple.slot // ninth column: slot name from the TAC KBP slot ontology. Optionally, this field may contain a second string separated from the first by a colon ":"
	val slot_value = -1 // tenth column: slot value equivalence class name generated by system
	val byte_range = "0-0" + triple.entity1 // eleventh column: inclusive byte range, e.g. "23-27" specifies five bytes. Byte numbering is zero-based

	
	override def toString(): String = 
	team_id + " " + system_id + " " + doc_id + " " + topic_id + " " + confidence + " " + relevance + " "  
	+ mention + " " + date_hour + " " + slot_value + " " + byte_range
	
	  
}