#include <vector>
#include "entity_match.h"

namespace streamcorpus {

  std::vector<streamcorpus::found_entity> alias_vector = {

    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Stuart_Powell_Field", "danville", "FAC", "Stuart Powell Field"),
    streamcorpus::found_entity("https://twitter.com/CorbinSpeedway", "danville", "FAC", "CorbinSpeedway"),
    streamcorpus::found_entity("https://twitter.com/CorbinSpeedway", "danville", "FAC", "Corbin Speedway"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/IDSIA", "deeplearning", "FAC", "IDSIA"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Corn_Belt_Power_Cooperative", "fargo", "FAC", "Corn Belt Power Cooperative"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo-Moorhead_Symphony_Orchestra", "fargo", "FAC", "Fargo-Moorhead Symphony Orchestra"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo_Air_Museum", "fargo", "FAC", "Fargo Air Museum"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hjemkomst_Center", "fargo", "FAC", "Hjemkomst Center"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hjemkomst_Center", "fargo", "FAC", "Heritage Hjemkomst Interpretive Center"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/John_D._Odegard_School_of_Aerospace_Sciences", "fargo", "FAC", "John D. Odegard School of Aerospace Sciences"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Red_River_Zoo", "fargo", "FAC", "Red River Zoo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Star_Lite_Motel", "fargo", "FAC", "Star Lite Motel"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Elysian_Charter_School", "hoboken", "FAC", "Elysian Charter School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Stevens_Cooperative_School", "hoboken", "FAC", "Stevens Cooperative School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Weehawken_Cove", "hoboken", "FAC", "Weehawken Cove"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Copper_Basin_Railway", "mining", "FAC", "Cooper Basin Railway"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hayden_Smelter", "mining", "FAC", "Hayden Smelter"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lewis_and_Clark_Landing", "mining", "FAC", "Lewis and Clark Landing"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Toquepala_mine", "mining", "FAC", "Toquepala mine"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Appleton_Museum_of_Art", "ocala", "FAC", "Appelton Museum of Art"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Appleton_Museum_of_Art", "ocala", "FAC", "Appelton Museum"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Don_Garlits_Museum_of_Drag_Racing", "ocala", "FAC", "Don Garlits Museum of Drag Racing"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Don_Garlits_Museum_of_Drag_Racing", "ocala", "FAC", "Don Garlits Museum"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Eighth_Street_Elementary_School", "ocala", "FAC", "Eighth Street Elementary School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lake_Weir_High_School", "ocala", "FAC", "Lake Weir High School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lake_Weir_High_School", "ocala", "FAC", "Lake Weir High"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Marion_Technical_Institute", "ocala", "FAC", "Marion Technical Institute"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Marion_Technical_Institute", "ocala", "FAC", "Marion Tech"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Osceola_Middle_School", "ocala", "FAC", "Osceola Middle School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Osceola_Middle_School", "ocala", "FAC", "Osceola Middle"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/The_Ritz_Apartment_(Ocala,_Florida)", "ocala", "FAC", "The Ritz Apartment Ocala, Florida"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/The_Ritz_Apartment_(Ocala,_Florida)", "ocala", "FAC", "The Ritz Apartment"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Great_American_Brass_Band_Festival", "danville", "ORG", "Great American Brass Band Festival"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Innovis_Health", "fargo", "ORG", "Innovis Health"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Innovis_Health", "fargo", "ORG", "Innovis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Reporter", "hoboken", "ORG", "Hoboken Reporter"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Reporter", "hoboken", "ORG", "Hoboken Newspaper"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Reporter", "hoboken", "ORG", "Hoboken paper"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Volunteer_Ambulance_Corps", "hoboken", "ORG", "Hoboken Volunteer Ambulance Corps"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(company)", "kba2012", "ORG", "Basic Element company"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(company)", "kba2012", "ORG", "Basic Element co"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(company)", "kba2012", "ORG", "Basic Element Companies"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(music_group)", "kba2012", "ORG", "Basic Element music groups"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(music_group)", "kba2012", "ORG", "Basic Element music"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Agroindustrial_Pomalca", "mining", "ORG", "Agroindustrial Pomalca"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Atacocha", "mining", "ORG", "Atacocha"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Austral_Group", "mining", "ORG", "Austral Group"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Cementos_Lima", "mining", "ORG", "Cementos Lima"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Dunkelvolk", "mining", "ORG", "Dunkelvolk"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gran%C3%A3_y_Montero", "mining", "ORG", "Granã y Montero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gran%C3%A3_y_Montero", "mining", "ORG", "Grana y Montero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gran%C3%A3_y_Montero", "mining", "ORG", "IGBVL"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Intergroup_Financial_Services", "mining", "ORG", "Intergroup Financial Services"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Luz_del_Sur", "mining", "ORG", "Luz del Sur"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/SIMSA", "mining", "ORG", "SIMSA"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scotiabank_Per%C3%BA", "mining", "ORG", "Scotiabank Perú"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scotiabank_Per%C3%BA", "mining", "ORG", "Scotiabank Peru"),
    streamcorpus::found_entity("https://twitter.com/BlossomCoffee", "startups", "ORG", "BlossomCoffee"),
    streamcorpus::found_entity("https://twitter.com/BlossomCoffee", "startups", "ORG", "Blossom Coffee"),
    streamcorpus::found_entity("https://twitter.com/FrankandOak", "startups", "ORG", "FrankandOak"),
    streamcorpus::found_entity("https://twitter.com/FrankandOak", "startups", "ORG", "Frank and Oak"),
    streamcorpus::found_entity("https://twitter.com/GandBcoffee", "startups", "ORG", "GandBcoffee"),
    streamcorpus::found_entity("https://twitter.com/WCoffeeResearch", "startups", "ORG", "WCoffeeResearch"),
    streamcorpus::found_entity("https://twitter.com/WCoffeeResearch", "startups", "ORG", "W Coffee Research"),
    streamcorpus::found_entity("https://twitter.com/evvnt", "startups", "ORG", "evvnt"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Benjamin_Bronfman", "bronfman", "PER", "Benjamin Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Charles_Bronfman", "bronfman", "PER", "Charles Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Clare_Bronfman", "bronfman", "PER", "Clare Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Jr.", "bronfman", "PER", "Edgar Bronfman, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Jr.", "bronfman", "PER", "Edgar Bronfman, Jr"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Jr.", "bronfman", "PER", "Edgar Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Jr.", "bronfman", "PER", "Edgar Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Jr.", "bronfman", "PER", "Efer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Sr.", "bronfman", "PER", "Edgar Bronfman, Sr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Sr.", "bronfman", "PER", "Edgar Bronfman, Sr"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Sr.", "bronfman", "PER", "Edgar Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Sr.", "bronfman", "PER", "Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Phyllis_Lambert", "bronfman", "PER", "Phyllis Lambert"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Sara_Bronfman", "bronfman", "PER", "Sara Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/DeAnne_Smith", "commedians", "PER", "DeAnne Smith"),
    streamcorpus::found_entity("https://twitter.com/RonFunches", "commedians", "PER", "RonFunches"),
    streamcorpus::found_entity("https://twitter.com/RonFunches", "commedians", "PER", "Ron Funches"),
    streamcorpus::found_entity("https://twitter.com/roryscovel", "commedians", "PER", "roryscovel"),
    streamcorpus::found_entity("https://twitter.com/roryscovel", "commedians", "PER", "rory scovel"),
    streamcorpus::found_entity("https://twitter.com/AlexJoHamilton", "danville", "PER", "Alex Jo Hamilton"),
    streamcorpus::found_entity("https://twitter.com/AlexJoHamilton", "danville", "PER", "AlexJoHamilton"),
    streamcorpus::found_entity("https://twitter.com/BobStovall", "danville", "PER", "BobStovall"),
    streamcorpus::found_entity("https://twitter.com/BobStovall", "danville", "PER", "Bob Stovall"),
    streamcorpus::found_entity("https://twitter.com/RobCaud", "danville", "PER", "RobCaud"),
    streamcorpus::found_entity("https://twitter.com/RobCaud", "danville", "PER", "Rob Caud"),
    streamcorpus::found_entity("https://twitter.com/danvillekyengr", "danville", "PER", "danvillekyengr"),
    streamcorpus::found_entity("https://twitter.com/danvillekyengr", "danville", "PER", "danville engineering"),
    streamcorpus::found_entity("https://twitter.com/danvillekyengr", "danville", "PER", "danville ky engineering"),
    streamcorpus::found_entity("https://twitter.com/tonyg203", "danville", "PER", "tonyg203"),
    streamcorpus::found_entity("https://twitter.com/tonyg203", "danville", "PER", "Tony Gray"),
    streamcorpus::found_entity("https://twitter.com/urbren00", "danville", "PER", "urbren00"),
    streamcorpus::found_entity("https://twitter.com/urbren00", "danville", "PER", "Brent Faulkner"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Geoffrey_E._Hinton", "deeplearning", "PER", "Geoffrey E. Hinton"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Geoffrey_E._Hinton", "deeplearning", "PER", "Geoffrey Hinton"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Geoffrey_E._Hinton", "deeplearning", "PER", "Geoffrey E Hinton"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "Léon Bottou"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "Leon Bottou"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Yann_LeCun", "deeplearning", "PER", "Yann LeCun"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Zoubin_Ghahramani", "deeplearning", "PER", "Zoubin Ghahramani"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Blair_Thoreson", "fargo", "PER", "Blair Thoer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Brenda_Weiler", "fargo", "PER", "Brenda Weiler"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carey_McWilliams_(marksman)", "fargo", "PER", "Carey McWilliams"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carey_McWilliams_(marksman)", "fargo", "PER", "Carey McWilliams marksman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Clark_Blaise", "fargo", "PER", "Clark Blaise"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Daniel_J._Crothers", "fargo", "PER", "Daniel J. Crothers"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Daniel_J._Crothers", "fargo", "PER", "Daniel J Crothers"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Daniel_J._Crothers", "fargo", "PER", "Daniel Crothers"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Danny_Irmen", "fargo", "PER", "Danny Irmen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/David_B._Danbom", "fargo", "PER", "David B. Danbom"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/David_B._Danbom", "fargo", "PER", "David B Danbom"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/David_B._Danbom", "fargo", "PER", "David Danbom"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Drew_Wrigley", "fargo", "PER", "Drew Wrigley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ed_Bok_Lee", "fargo", "PER", "Ed Bok Lee"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo_Moorhead_Derby_Girls", "fargo", "PER", "Fargo Moorhead Derby Girls"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/George_Sinner", "fargo", "PER", "George Sinner"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gretchen_Hoffman", "fargo", "PER", "Gretchen Hoffman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jamie_Parsley", "fargo", "PER", "Jamie Parsley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jasper_Schneider", "fargo", "PER", "Jasper Schneider"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeff_Severson", "fargo", "PER", "Jeff Severson"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jennifer_Baumgardner", "fargo", "PER", "Jennifer Baumgardner"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jim_Poolman", "fargo", "PER", "Jim Poolman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/John_H._Lang", "fargo", "PER", "John H. Lang"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/John_H._Lang", "fargo", "PER", "John H Lang"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joshua_Boschee", "fargo", "PER", "Joshua Boschee"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ken_Fowler", "fargo", "PER", "Ken Fowler"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Keri_Hehn", "fargo", "PER", "Keri Hehn"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Olaus_Murie", "fargo", "PER", "Olaus Murie"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Paul_Johnsgard", "fargo", "PER", "Paul Johnsgard"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Paul_Marquart", "fargo", "PER", "Paul Marquart"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Richard_Edlund", "fargo", "PER", "Richard Edlund"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Richard_W._Goldberg", "fargo", "PER", "Richard W. Goldberg"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Richard_W._Goldberg", "fargo", "PER", "Richard W Goldberg"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Richard_W._Goldberg", "fargo", "PER", "Richard Goldberg"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Susan_Krieg", "fargo", "PER", "Susan Krieg"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_P._Gerberding", "fargo", "PER", "William P. Gerberding"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_P._Gerberding", "fargo", "PER", "William P Gerberding"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_P._Gerberding", "fargo", "PER", "William Gerberding"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Anaïs Croze"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Anais Croze"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Gwenaëlle Aubry"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Gwenaelle Aubry"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Nicolas Schöffer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Nicolas Schoffer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Théo Mercier"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Theo Mercier"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Chiara_Nappi", "hep", "PER", "Chiara Nappi"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Eva_Silverstein", "hep", "PER", "Eva Silverstein"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Matt_Witten", "hep", "PER", "Matt Witten"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Shamit_Kachru", "hep", "PER", "Shamit Kachru"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Angelo_Savoldi", "hoboken", "PER", "Angelo Savoldi"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bernard_Kenny", "hoboken", "PER", "Bernard Kenny"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bob_Bert", "hoboken", "PER", "Bob Bert"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carl_Chang_(tennis)", "hoboken", "PER", "Carl Chang tennis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carl_Chang_(tennis)", "hoboken", "PER", "Carl Chang"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carla_Katz", "hoboken", "PER", "Carla Katz"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Derrick_Alston", "hoboken", "PER", "Derrick Alston"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Frank_Winters", "hoboken", "PER", "Frank Winters"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Henry_Gutierrez", "hoboken", "PER", "Henry Gutierrez"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jack_Lazorko", "hoboken", "PER", "Jack Lazorko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeff_Tamarkin", "hoboken", "PER", "Jeff Tamarkin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joanne_Borgella", "hoboken", "PER", "Joanne Borgella"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ken_Freedman", "hoboken", "PER", "Ken Freedman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Klaus_Grutzka", "hoboken", "PER", "Klaus Grutzka"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mark_SaFranko", "hoboken", "PER", "Mark SaFranko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Maurice_Fitzgibbons", "hoboken", "PER", "Maurice Fitzgibbons"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Pat_Dapuzzo", "hoboken", "PER", "Pat Dapuzzo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruben_J._Ramos", "hoboken", "PER", "Ruben J. Ramos"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruben_J._Ramos", "hoboken", "PER", "Ruben J Ramos"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruben_J._Ramos", "hoboken", "PER", "Ruben Ramos"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Tilo_Rivas", "hoboken", "PER", "Tilo Rivas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Miller_(writer)", "hoboken", "PER", "William H. Miller writer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Miller_(writer)", "hoboken", "PER", "William H. Miller"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Miller_(writer)", "hoboken", "PER", "William H Miller"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Miller_(writer)", "hoboken", "PER", "William Miller"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Aharon_Barak", "kba2012", "PER", "Aharon Barak"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Alex Kapranos"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alexander_McCall_Smith", "kba2012", "PER", "Alexander McCall Smith"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Annie_Laurie_Gaylor", "kba2012", "PER", "Annie Laurie Gaylor"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bill_Coen", "kba2012", "PER", "Bill Coen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Boris Berezovsky businessman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Boris Berezovsky"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(pianist)", "kba2012", "PER", "Boris Berezovsky pianist"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(pianist)", "kba2012", "PER", "Boris Vadimovich Berezovsky"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Charlie_Savage", "kba2012", "PER", "Charlie Savage"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Darren_Rowse", "kba2012", "PER", "Darren Rowse"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Douglas_Carswell", "kba2012", "PER", "Douglas Carswell"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Frederick_M._Lawrence", "kba2012", "PER", "Frederick M. Lawrence"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Frederick_M._Lawrence", "kba2012", "PER", "Fredrick M Lawrence"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Frederick_M._Lawrence", "kba2012", "PER", "Fredrick Lawrence"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ikuhisa_Minowa", "kba2012", "PER", "Ikuhisa Minowa"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/James_McCartney", "kba2012", "PER", "James McCartney"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jim_Steyer", "kba2012", "PER", "Jim Steyer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lisa_Bloom", "kba2012", "PER", "Lisa Bloom"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lovebug_Starski", "kba2012", "PER", "Lovebug Starski"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mario_Garnero", "kba2012", "PER", "Mario Garnero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Masaru Emoto"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nassim Nicholas Taleb"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Rodrigo_Pimentel", "kba2012", "PER", "Rodrigo Pimentel"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Roustam_Tariko", "kba2012", "PER", "Roustam Tariko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Ruth Rendell"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Satoshi_Ishii", "kba2012", "PER", "Satoshi Ishii"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Vladimir_Potanin", "kba2012", "PER", "Vladimir Potanin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "William Cohen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_D._Cohan", "kba2012", "PER", "William D. Cohan"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_D._Cohan", "kba2012", "PER", "William D Cohan"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_D._Cohan", "kba2012", "PER", "William Cohan"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Gates,_Sr", "kba2012", "PER", "William H. Gates, Sr"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Gates,_Sr", "kba2012", "PER", "William H. Gates"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Gates,_Sr", "kba2012", "PER", "William H Gates"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Buddy MacKay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Chuck_Pankow", "ocala", "PER", "Chuck Pankow"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Haven_Denney", "ocala", "PER", "Haven Denney"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeremy_McKinnon", "ocala", "PER", "Jeremy McKinnon"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joey_Mantia", "ocala", "PER", "Joey Mantia"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Judd_Davis", "ocala", "PER", "Judd Davis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lorenzo_Williams_(basketball)", "ocala", "PER", "Lorenzo Williams basketball"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lorenzo_Williams_(basketball)", "ocala", "PER", "Lorenzo Williams"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Randy_Ewers", "ocala", "PER", "Randy Ewers"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Reid_Nichols", "ocala", "PER", "Reid Nichols"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scot_Brantley", "ocala", "PER", "Scot Brantley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scot_Brantley", "ocala", "PER", "Coach Brantley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scot_Brantley", "ocala", "PER", "Scot Eugene Brantley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Sean_Hampton", "ocala", "PER", "Sean Hampton"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Travis_Mays", "ocala", "PER", "Travis Mays"),
    streamcorpus::found_entity("https://twitter.com/BartowMcDonald", "ocala", "PER", "BartowMcDonald"),
    streamcorpus::found_entity("https://twitter.com/BartowMcDonald", "ocala", "PER", "Bartow McDonald"),
    streamcorpus::found_entity("https://twitter.com/KentGuinn4Mayor", "ocala", "PER", "KentGuinn4Mayor"),
    streamcorpus::found_entity("https://twitter.com/KentGuinn4Mayor", "ocala", "PER", "Kent Guinn 4 Mayor"),
    streamcorpus::found_entity("https://twitter.com/KentGuinn4Mayor", "ocala", "PER", "Ken Guinn"),
    streamcorpus::found_entity("https://twitter.com/bobplaisted", "ocala", "PER", "bobplaisted"),
    streamcorpus::found_entity("https://twitter.com/bobplaisted", "ocala", "PER", "bob plaisted"),
    streamcorpus::found_entity("https://twitter.com/redmondmusic", "ocala", "PER", "redmondmusic"),
    streamcorpus::found_entity("https://twitter.com/redmondmusic", "ocala", "PER", "redmond music"),
    streamcorpus::found_entity("https://twitter.com/sandrafriend", "ocala", "PER", "sandrafriend"),
    streamcorpus::found_entity("https://twitter.com/sandrafriend", "ocala", "PER", "sandra friend"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joshua_Zetumer", "screenwriters", "PER", "Joshua Zetumer"),
    streamcorpus::found_entity("https://twitter.com/MissMarcel", "screenwriters", "PER", "MissMarcel"),
    streamcorpus::found_entity("https://twitter.com/MissMarcel", "screenwriters", "PER", "Miss Marcel"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Barbara_Liskov", "turing", "PER", "Barbara Liskov"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando J. Corbató"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando J Corbató"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando Corbató"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando Corbato"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Juris_Hartmanis", "turing", "PER", "Juris Hartmanis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Shafi_Goldwasser", "turing", "PER", "Shafi Goldwasser")
  };

 }; // streamcorpus 

