#include <vector>
#include "entity_match.h"

namespace streamcorpus {

  std::vector<streamcorpus::found_entity> alias_vector = {

    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Stuart_Powell_Field", "danville", "FAC", "KDVK"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Stuart_Powell_Field", "danville", "FAC", "Stuart_Powell_Field"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Stuart_Powell_Field", "danville", "FAC", "Stuart Powell Field"),
    streamcorpus::found_entity("https://twitter.com/CorbinSpeedway", "danville", "FAC", "CorbinSpeedway"),
    streamcorpus::found_entity("https://twitter.com/CorbinSpeedway", "danville", "FAC", "Corbin Speedway"),
    streamcorpus::found_entity("https://twitter.com/CorbinSpeedway", "danville", "FAC", "Speedway, Corbin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/IDSIA", "deeplearning", "FAC", "Dalle Molle Institute for Artificial Intelligence Research"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/IDSIA", "deeplearning", "FAC", "IDSIA"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Corn_Belt_Power_Cooperative", "fargo", "FAC", "Corn Belt Power Cooperative"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Corn_Belt_Power_Cooperative", "fargo", "FAC", "The Corn Belt Power Cooperative"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Corn_Belt_Power_Cooperative", "fargo", "FAC", "Corn_Belt_Power_Cooperative"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo-Moorhead_Symphony_Orchestra", "fargo", "FAC", "Fargo-Moorhead Symphony Orchestra"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo-Moorhead_Symphony_Orchestra", "fargo", "FAC", "Fargo-Moorhead_Symphony_Orchestra"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo_Air_Museum", "fargo", "FAC", "Fargo Air Museum"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo_Air_Museum", "fargo", "FAC", "Fargo_Air_Museum"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo_Air_Museum", "fargo", "FAC", "Fargo Airplane Museum"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hjemkomst_Center", "fargo", "FAC", "Hjemkomst_Center"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hjemkomst_Center", "fargo", "FAC", "Hjemkomst Center"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hjemkomst_Center", "fargo", "FAC", "Center, Hjemkomst"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hjemkomst_Center", "fargo", "FAC", "Historical and Cultural Society of Clay County."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hjemkomst_Center", "fargo", "FAC", "The Heritage Hjemkomst Interpretive Center"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/John_D._Odegard_School_of_Aerospace_Sciences", "fargo", "FAC", "Jdosas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/John_D._Odegard_School_of_Aerospace_Sciences", "fargo", "FAC", "Aerospace, UND"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/John_D._Odegard_School_of_Aerospace_Sciences", "fargo", "FAC", "John_D._Odegard_School_of_Aerospace_Sciences"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/John_D._Odegard_School_of_Aerospace_Sciences", "fargo", "FAC", "UND Aerospace"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/John_D._Odegard_School_of_Aerospace_Sciences", "fargo", "FAC", "John D Odegard School of Aerospace Sciences"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/John_D._Odegard_School_of_Aerospace_Sciences", "fargo", "FAC", "John D. Odegard School of Aerospace Sciences"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Red_River_Zoo", "fargo", "FAC", "Red River Zoo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Red_River_Zoo", "fargo", "FAC", "Red_River_Zoo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Star_Lite_Motel", "fargo", "FAC", "Charley's Motel"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Star_Lite_Motel", "fargo", "FAC", "Motel, Charley's"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Star_Lite_Motel", "fargo", "FAC", "Star Lite Motel"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Star_Lite_Motel", "fargo", "FAC", "Star_Lite_Motel"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Elysian_Charter_School", "hoboken", "FAC", "Elysian_Charter_School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Elysian_Charter_School", "hoboken", "FAC", "Weintraub, Joanna"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Elysian_Charter_School", "hoboken", "FAC", "Joanna Weintraub"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Elysian_Charter_School", "hoboken", "FAC", "Elysian Charter School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Elysian_Charter_School", "hoboken", "FAC", "Elysian Charter School of Hoboken"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Stevens_Cooperative_School", "hoboken", "FAC", "Zoe Hauser"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Stevens_Cooperative_School", "hoboken", "FAC", "Stevens_Cooperative_School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Stevens_Cooperative_School", "hoboken", "FAC", "Hauser, Zoe"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Stevens_Cooperative_School", "hoboken", "FAC", "Stevens Cooperative School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Weehawken_Cove", "hoboken", "FAC", "Weehawken_Cove"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Weehawken_Cove", "hoboken", "FAC", "Weehawken Cove"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Weehawken_Cove", "hoboken", "FAC", "Cove, Hoboken"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Weehawken_Cove", "hoboken", "FAC", "Cove, Weehawken"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Weehawken_Cove", "hoboken", "FAC", "Hoboken Cove"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Weehawken_Cove", "hoboken", "FAC", "North Hoboken Harbor"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Weehawken_Cove", "hoboken", "FAC", "Hoboken's Inner Harbor"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Weehawken_Cove", "hoboken", "FAC", "Weehawken Cove (North Hoboken Harbor)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Copper_Basin_Railway", "mining", "FAC", "CBRY"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Copper_Basin_Railway", "mining", "FAC", "Copper Basin Railway"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Copper_Basin_Railway", "mining", "FAC", "Copper_Basin_Railway"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hayden_Smelter", "mining", "FAC", "Hayden Smelter"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hayden_Smelter", "mining", "FAC", "Smelter, Hayden"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hayden_Smelter", "mining", "FAC", "Hayden_Smelter"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lewis_and_Clark_Landing", "mining", "FAC", "Lewis & Clark Landing"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lewis_and_Clark_Landing", "mining", "FAC", "Lewis_and_Clark_Landing"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lewis_and_Clark_Landing", "mining", "FAC", "Lewis and Clark Landing"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Toquepala_mine", "mining", "FAC", "Toquepala_mine"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Toquepala_mine", "mining", "FAC", "Toquepala mine"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Toquepala_mine", "mining", "FAC", "mine, Toquepala"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Appleton_Museum_of_Art", "ocala", "FAC", "Appleton_Museum_of_Art"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Appleton_Museum_of_Art", "ocala", "FAC", "Arthur I. Appleton"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Appleton_Museum_of_Art", "ocala", "FAC", "Museum, Appleton"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Appleton_Museum_of_Art", "ocala", "FAC", "Appleton Museum"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Appleton_Museum_of_Art", "ocala", "FAC", "Appleton museum of art"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Appleton_Museum_of_Art", "ocala", "FAC", "Appleton Museum of Art"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Don_Garlits_Museum_of_Drag_Racing", "ocala", "FAC", "Don_Garlits_Museum_of_Drag_Racing"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Don_Garlits_Museum_of_Drag_Racing", "ocala", "FAC", "Don Garlits Museum of Drag Racing"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Eighth_Street_Elementary_School", "ocala", "FAC", "Eighth Street Elementary School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Eighth_Street_Elementary_School", "ocala", "FAC", "Eighth_Street_Elementary_School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lake_Weir_High_School", "ocala", "FAC", "Lake_Weir_High_School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lake_Weir_High_School", "ocala", "FAC", "Lake Weir High School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Marion_Technical_Institute", "ocala", "FAC", "Marion_Technical_Institute"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Marion_Technical_Institute", "ocala", "FAC", "Marion Technical Institute"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Marion_Technical_Institute", "ocala", "FAC", "Life at MTI"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Osceola_Middle_School", "ocala", "FAC", "Osceola_Middle_School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Osceola_Middle_School", "ocala", "FAC", "Osceola Middle School"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/The_Ritz_Apartment_(Ocala,_Florida)", "ocala", "FAC", "Ritz Apartment"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/The_Ritz_Apartment_(Ocala,_Florida)", "ocala", "FAC", "The_Ritz_Apartment_"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/The_Ritz_Apartment_(Ocala,_Florida)", "ocala", "FAC", "Apartment, Ritz"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/The_Ritz_Apartment_(Ocala,_Florida)", "ocala", "FAC", "The Ritz-Ocala Apartments"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/The_Ritz_Apartment_(Ocala,_Florida)", "ocala", "FAC", "The Acker-Ritz Apartments"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/The_Ritz_Apartment_(Ocala,_Florida)", "ocala", "FAC", "The Ritz Apartment (Ocala, Florida)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/The_Ritz_Apartment_(Ocala,_Florida)", "ocala", "FAC", "The_Ritz_Apartment_(Ocala,_Florida)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/The_Ritz_Apartment_(Ocala,_Florida)", "ocala", "FAC", "The Ritz Apartment"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Great_American_Brass_Band_Festival", "danville", "ORG", "Great_American_Brass_Band_Festival"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Great_American_Brass_Band_Festival", "danville", "ORG", "Great American Brass Band Festival"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Innovis_Health", "fargo", "ORG", "Innovis_Health"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Innovis_Health", "fargo", "ORG", "Innovis Health"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Innovis_Health", "fargo", "ORG", "Health, Innovis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Reporter", "hoboken", "ORG", "Hoboken_Reporter"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Reporter", "hoboken", "ORG", "The Hoboken Reporter"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Reporter", "hoboken", "ORG", "Hoboken Reporter"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Reporter", "hoboken", "ORG", "Reporter, Hoboken"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Volunteer_Ambulance_Corps", "hoboken", "ORG", "Hoboken_Volunteer_Ambulance_Corps"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Volunteer_Ambulance_Corps", "hoboken", "ORG", "Hoboken Volunteer Ambulance Corps"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Volunteer_Ambulance_Corps", "hoboken", "ORG", "Hoboken EMS"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Volunteer_Ambulance_Corps", "hoboken", "ORG", "HVAC"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Hoboken_Volunteer_Ambulance_Corps", "hoboken", "ORG", "EMS, Hoboken"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(company)", "kba2012", "ORG", "Basic Element"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(company)", "kba2012", "ORG", "Basic Element Group"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(company)", "kba2012", "ORG", "Element, Basic"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(company)", "kba2012", "ORG", "Basic Element (corp)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(company)", "kba2012", "ORG", "Basic_Element_(company)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(company)", "kba2012", "ORG", "Basic Element (company)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(company)", "kba2012", "ORG", "Basic_Element_"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(music_group)", "kba2012", "ORG", "Basic_Element_(music_group)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(music_group)", "kba2012", "ORG", "Basic Element"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(music_group)", "kba2012", "ORG", "Basic Element (music group)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(music_group)", "kba2012", "ORG", "Element, Basic"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Basic_Element_(music_group)", "kba2012", "ORG", "Basic_Element_"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Agroindustrial_Pomalca", "mining", "ORG", "Pomalca"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Agroindustrial_Pomalca", "mining", "ORG", "Agroindustrial Pomalca"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Agroindustrial_Pomalca", "mining", "ORG", "Agroindustrial_Pomalca"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Agroindustrial_Pomalca", "mining", "ORG", "Pomalca, Agroindustrial"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Atacocha", "mining", "ORG", "Atacocha"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Austral_Group", "mining", "ORG", "Austral Group"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Austral_Group", "mining", "ORG", "Group, Austral"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Austral_Group", "mining", "ORG", "Austral_Group"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Cementos_Lima", "mining", "ORG", "Cementos_Lima"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Cementos_Lima", "mining", "ORG", "Cementos Lima"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Cementos_Lima", "mining", "ORG", "Lima, Cementos"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Dunkelvolk", "mining", "ORG", "Dunkelvolk"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gran%C3%A3_y_Montero", "mining", "ORG", "Gran%C3%A3 y Montero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gran%C3%A3_y_Montero", "mining", "ORG", "Grana y Montero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gran%C3%A3_y_Montero", "mining", "ORG", "Gran� y Montero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gran%C3%A3_y_Montero", "mining", "ORG", "Graña y Montero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gran%C3%A3_y_Montero", "mining", "ORG", "Gran�_y_Montero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gran%C3%A3_y_Montero", "mining", "ORG", "Gran%C3%A3_y_Montero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Intergroup_Financial_Services", "mining", "ORG", "Intergroup Financial Services"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Intergroup_Financial_Services", "mining", "ORG", "Intergroup_Financial_Services"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Luz_del_Sur", "mining", "ORG", "Luz_del_Sur"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Luz_del_Sur", "mining", "ORG", "Luz del Sur"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/SIMSA", "mining", "ORG", "SIMSA"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scotiabank_Per%C3%BA", "mining", "ORG", "Per%C3%BA, Scotiabank"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scotiabank_Per%C3%BA", "mining", "ORG", "Scotiabank_Per�"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scotiabank_Per%C3%BA", "mining", "ORG", "Scotiabank_Per%C3%BA"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scotiabank_Per%C3%BA", "mining", "ORG", "Per�, Scotiabank"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scotiabank_Per%C3%BA", "mining", "ORG", "Scotiabank Per�"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scotiabank_Per%C3%BA", "mining", "ORG", "Scotiabank Per%C3%BA"),
    streamcorpus::found_entity("https://twitter.com/BlossomCoffee", "startups", "ORG", "BlossomCoffee"),
    streamcorpus::found_entity("https://twitter.com/BlossomCoffee", "startups", "ORG", "Blossom Coffee"),
    streamcorpus::found_entity("https://twitter.com/BlossomCoffee", "startups", "ORG", "Coffee, Blossom"),
    streamcorpus::found_entity("https://twitter.com/FrankandOak", "startups", "ORG", "Frank & Oak"),
    streamcorpus::found_entity("https://twitter.com/FrankandOak", "startups", "ORG", "Frank and Oak"),
    streamcorpus::found_entity("https://twitter.com/FrankandOak", "startups", "ORG", "Oak, Frankand"),
    streamcorpus::found_entity("https://twitter.com/FrankandOak", "startups", "ORG", "Frankand Oak"),
    streamcorpus::found_entity("https://twitter.com/FrankandOak", "startups", "ORG", "FrankHelps"),
    streamcorpus::found_entity("https://twitter.com/FrankandOak", "startups", "ORG", "FrankandOak"),
    streamcorpus::found_entity("https://twitter.com/GandBcoffee", "startups", "ORG", "Bcoffee, Gand"),
    streamcorpus::found_entity("https://twitter.com/GandBcoffee", "startups", "ORG", "Glanville & Babinski"),
    streamcorpus::found_entity("https://twitter.com/GandBcoffee", "startups", "ORG", "Glanville and Babinski"),
    streamcorpus::found_entity("https://twitter.com/GandBcoffee", "startups", "ORG", "Gand Bcoffee"),
    streamcorpus::found_entity("https://twitter.com/GandBcoffee", "startups", "ORG", "GandBcoffee"),
    streamcorpus::found_entity("https://twitter.com/WCoffeeResearch", "startups", "ORG", "WCoffeeResearch"),
    streamcorpus::found_entity("https://twitter.com/WCoffeeResearch", "startups", "ORG", "WCoffee Research"),
    streamcorpus::found_entity("https://twitter.com/WCoffeeResearch", "startups", "ORG", "Research, WCoffee"),
    streamcorpus::found_entity("https://twitter.com/WCoffeeResearch", "startups", "ORG", "WorldCoffeeResearch"),
    streamcorpus::found_entity("https://twitter.com/WCoffeeResearch", "startups", "ORG", "World Coffee Research"),
    streamcorpus::found_entity("https://twitter.com/evvnt", "startups", "ORG", "evvnt"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Benjamin_Bronfman", "bronfman", "PER", "Bronfman, Benjamin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Benjamin_Bronfman", "bronfman", "PER", "Benjamin_Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Benjamin_Bronfman", "bronfman", "PER", "Ben Brewer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Benjamin_Bronfman", "bronfman", "PER", "Brewer, Ben"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Benjamin_Bronfman", "bronfman", "PER", "Benjamin Zachary Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Benjamin_Bronfman", "bronfman", "PER", "Benjamin Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Charles_Bronfman", "bronfman", "PER", "Charles_Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Charles_Bronfman", "bronfman", "PER", "Charles Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Charles_Bronfman", "bronfman", "PER", "Charles Rosner Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Charles_Bronfman", "bronfman", "PER", "Bronfman, Charles"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Clare_Bronfman", "bronfman", "PER", "Clare_Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Clare_Bronfman", "bronfman", "PER", "Clare Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Clare_Bronfman", "bronfman", "PER", "Bronfman, Clare"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Jr.", "bronfman", "PER", "Edgar Bronfman Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Jr.", "bronfman", "PER", "Edgar Miles Bronfman, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Jr.", "bronfman", "PER", "Edgar Bronfman, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Jr.", "bronfman", "PER", "Edgar_Bronfman,_Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Sr.", "bronfman", "PER", "Edgar Bronfman, Sr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Sr.", "bronfman", "PER", "Edgar Bronfman Sr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Sr.", "bronfman", "PER", "Edgar Miles Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Sr.", "bronfman", "PER", "Edgar_Bronfman,_Sr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Sr.", "bronfman", "PER", "Edgar Miles Bronfman Sr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Sr.", "bronfman", "PER", "Edgar M. Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Edgar_Bronfman,_Sr.", "bronfman", "PER", "Edgar Miles Bronfman, Sr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Phyllis_Lambert", "bronfman", "PER", "Phyllis Barbara Lambert"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Phyllis_Lambert", "bronfman", "PER", "Phyllis Lambert"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Phyllis_Lambert", "bronfman", "PER", "Phyllis Barbara Lambert, CC, GOQ, OAL, FRAIC, FRSC, RCA"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Phyllis_Lambert", "bronfman", "PER", "Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Phyllis_Lambert", "bronfman", "PER", "Lambert, Phyllis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Phyllis_Lambert", "bronfman", "PER", "Phyllis_Lambert"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Sara_Bronfman", "bronfman", "PER", "Sara_Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Sara_Bronfman", "bronfman", "PER", "Bronfman, Sara"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Sara_Bronfman", "bronfman", "PER", "Sara Bronfman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/DeAnne_Smith", "commedians", "PER", "DeAnne Smith"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/DeAnne_Smith", "commedians", "PER", "Smith, DeAnne"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/DeAnne_Smith", "commedians", "PER", "DeAnne_Smith"),
    streamcorpus::found_entity("https://twitter.com/RonFunches", "commedians", "PER", "Funches, Ron"),
    streamcorpus::found_entity("https://twitter.com/RonFunches", "commedians", "PER", "RonFunches"),
    streamcorpus::found_entity("https://twitter.com/RonFunches", "commedians", "PER", "Ron Funches"),
    streamcorpus::found_entity("https://twitter.com/RonFunches", "commedians", "PER", "Funches, Ronald"),
    streamcorpus::found_entity("https://twitter.com/RonFunches", "commedians", "PER", "Ronald Funches"),
    streamcorpus::found_entity("https://twitter.com/roryscovel", "commedians", "PER", "Scovel, Rory"),
    streamcorpus::found_entity("https://twitter.com/roryscovel", "commedians", "PER", "Rory Scovel"),
    streamcorpus::found_entity("https://twitter.com/roryscovel", "commedians", "PER", "roryscovel"),
    streamcorpus::found_entity("https://twitter.com/AlexJoHamilton", "danville", "PER", "Alexandra Hamilton"),
    streamcorpus::found_entity("https://twitter.com/AlexJoHamilton", "danville", "PER", "Hamilton, Alexandra"),
    streamcorpus::found_entity("https://twitter.com/AlexJoHamilton", "danville", "PER", "Alex J. Hamilton"),
    streamcorpus::found_entity("https://twitter.com/AlexJoHamilton", "danville", "PER", "AlexJoHamilton"),
    streamcorpus::found_entity("https://twitter.com/AlexJoHamilton", "danville", "PER", "Alexandra J Hamilton"),
    streamcorpus::found_entity("https://twitter.com/AlexJoHamilton", "danville", "PER", "Alex Jo Hamilton"),
    streamcorpus::found_entity("https://twitter.com/AlexJoHamilton", "danville", "PER", "Hamilton, Alex"),
    streamcorpus::found_entity("https://twitter.com/BobStovall", "danville", "PER", "Stovall, Bob"),
    streamcorpus::found_entity("https://twitter.com/BobStovall", "danville", "PER", "Bob Stovall"),
    streamcorpus::found_entity("https://twitter.com/BobStovall", "danville", "PER", "BobStovall"),
    streamcorpus::found_entity("https://twitter.com/RobCaud", "danville", "PER", "Rob Caud"),
    streamcorpus::found_entity("https://twitter.com/RobCaud", "danville", "PER", "Rob Caudill"),
    streamcorpus::found_entity("https://twitter.com/RobCaud", "danville", "PER", "Caudill, Rob"),
    streamcorpus::found_entity("https://twitter.com/RobCaud", "danville", "PER", "Caud, Rob"),
    streamcorpus::found_entity("https://twitter.com/RobCaud", "danville", "PER", "RobCaudill"),
    streamcorpus::found_entity("https://twitter.com/RobCaud", "danville", "PER", "RobCaud"),
    streamcorpus::found_entity("https://twitter.com/danvillekyengr", "danville", "PER", "danville ky engineering"),
    streamcorpus::found_entity("https://twitter.com/danvillekyengr", "danville", "PER", "danvillekyengr"),
    streamcorpus::found_entity("https://twitter.com/danvillekyengr", "danville", "PER", "danville engineering"),
    streamcorpus::found_entity("https://twitter.com/tonyg203", "danville", "PER", "tonyg203"),
    streamcorpus::found_entity("https://twitter.com/tonyg203", "danville", "PER", "Tony Gray"),
    streamcorpus::found_entity("https://twitter.com/tonyg203", "danville", "PER", "Gray, Tony"),
    streamcorpus::found_entity("https://twitter.com/urbren00", "danville", "PER", "Faulkner, Brent"),
    streamcorpus::found_entity("https://twitter.com/urbren00", "danville", "PER", "urbren00"),
    streamcorpus::found_entity("https://twitter.com/urbren00", "danville", "PER", "brent music reviews"),
    streamcorpus::found_entity("https://twitter.com/urbren00", "danville", "PER", "brentmusicreviews"),
    streamcorpus::found_entity("https://twitter.com/urbren00", "danville", "PER", "Brent Faulkner"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Geoffrey_E._Hinton", "deeplearning", "PER", "Geoffrey E. Hinton"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Geoffrey_E._Hinton", "deeplearning", "PER", "Hinton, Geoffrey"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Geoffrey_E._Hinton", "deeplearning", "PER", "Geoffrey_E._Hinton"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Geoffrey_E._Hinton", "deeplearning", "PER", "Geoffrey Hinton"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "Bottou, Léon"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "Bottou, Leon"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "Leon Bottou"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "L�on Bottou"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "L%C3%A9on_Bottou"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "Léon Bottou"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "Bottou, L%C3%A9on"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "L�on_Bottou"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "L%C3%A9on Bottou"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/L%C3%A9on_Bottou", "deeplearning", "PER", "Bottou, L�on"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Yann_LeCun", "deeplearning", "PER", "LeCun, Yann"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Yann_LeCun", "deeplearning", "PER", "Yann_LeCun"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Yann_LeCun", "deeplearning", "PER", "Cun, Yann_Le"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Yann_LeCun", "deeplearning", "PER", "Yann_Le Cun"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Yann_LeCun", "deeplearning", "PER", "Yann LeCun"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Yann_LeCun", "deeplearning", "PER", "Yann Le Cun"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Zoubin_Ghahramani", "deeplearning", "PER", "Zoubin_Ghahramani"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Zoubin_Ghahramani", "deeplearning", "PER", "Ghahramani, Zoubin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Zoubin_Ghahramani", "deeplearning", "PER", "Zoubin Ghahramani"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Blair_Thoreson", "fargo", "PER", "Blair B. Thoreson"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Blair_Thoreson", "fargo", "PER", "Thoreson, Blair"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Blair_Thoreson", "fargo", "PER", "Blair Thoreson"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Blair_Thoreson", "fargo", "PER", "Blair_Thoreson"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Brenda_Weiler", "fargo", "PER", "Brenda Weiler"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Brenda_Weiler", "fargo", "PER", "weiler, Brenda"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Brenda_Weiler", "fargo", "PER", "Brenda weiler"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Brenda_Weiler", "fargo", "PER", "Brenda_Weiler"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Brenda_Weiler", "fargo", "PER", "Weiler, Brenda"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carey_McWilliams_(marksman)", "fargo", "PER", "Carey_McWilliams_"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carey_McWilliams_(marksman)", "fargo", "PER", "Carey McWilliams (marksman)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carey_McWilliams_(marksman)", "fargo", "PER", "Williams_, Carey_Mc"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carey_McWilliams_(marksman)", "fargo", "PER", "Carey McWilliams"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carey_McWilliams_(marksman)", "fargo", "PER", "Carey_Mc Williams_"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carey_McWilliams_(marksman)", "fargo", "PER", "Carey_McWilliams_(marksman)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carey_McWilliams_(marksman)", "fargo", "PER", "Williams_(marksman), Carey_Mc"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carey_McWilliams_(marksman)", "fargo", "PER", "Carey_Mc Williams_(marksman)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carey_McWilliams_(marksman)", "fargo", "PER", "McWilliams, Carey"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Clark_Blaise", "fargo", "PER", "Blaise, Clark"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Clark_Blaise", "fargo", "PER", "Clark_Blaise"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Clark_Blaise", "fargo", "PER", "Clark Blaise"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Daniel_J._Crothers", "fargo", "PER", "Daniel J. Crothers"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Daniel_J._Crothers", "fargo", "PER", "Crothers, Daniel"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Daniel_J._Crothers", "fargo", "PER", "Daniel_J._Crothers"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Daniel_J._Crothers", "fargo", "PER", "Daniel John Crothers"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Daniel_J._Crothers", "fargo", "PER", "Daniel Crothers"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Danny_Irmen", "fargo", "PER", "Danny Irmen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Danny_Irmen", "fargo", "PER", "Danny_Irmen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Danny_Irmen", "fargo", "PER", "Irmen, Danny"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/David_B._Danbom", "fargo", "PER", "David Danbom"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/David_B._Danbom", "fargo", "PER", "Why Americans Value Rural Life"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/David_B._Danbom", "fargo", "PER", "David B. Danbom"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/David_B._Danbom", "fargo", "PER", "Danbom, David"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/David_B._Danbom", "fargo", "PER", "David_B._Danbom"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Drew_Wrigley", "fargo", "PER", "Drew_Wrigley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Drew_Wrigley", "fargo", "PER", "Drew Howard Wrigley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Drew_Wrigley", "fargo", "PER", "Drew Wrigley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Drew_Wrigley", "fargo", "PER", "Wrigley, Drew"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ed_Bok_Lee", "fargo", "PER", "Ed_Bok_Lee"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo_Moorhead_Derby_Girls", "fargo", "PER", "Fargo Moorehead Derby Girls"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo_Moorhead_Derby_Girls", "fargo", "PER", "Fargo Moorhead Derby Girls"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo_Moorhead_Derby_Girls", "fargo", "PER", "Fargo-Moorhead Derby Girls"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fargo_Moorhead_Derby_Girls", "fargo", "PER", "Fargo_Moorhead_Derby_Girls"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/George_Sinner", "fargo", "PER", "George A. Sinner"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/George_Sinner", "fargo", "PER", "George Albert Sinner"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/George_Sinner", "fargo", "PER", "Sinner, George"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/George_Sinner", "fargo", "PER", "George Sinner"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/George_Sinner", "fargo", "PER", "George_Sinner"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gretchen_Hoffman", "fargo", "PER", "Hoffman, Gretchen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gretchen_Hoffman", "fargo", "PER", "Gretchen M. Hoffman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gretchen_Hoffman", "fargo", "PER", "Gretchen Hoffman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gretchen_Hoffman", "fargo", "PER", "Gretchen_Hoffman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jamie_Parsley", "fargo", "PER", "Jamie_Parsley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jamie_Parsley", "fargo", "PER", "Parsley, Jamie"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jamie_Parsley", "fargo", "PER", "Jamie Parsley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jasper_Schneider", "fargo", "PER", "Schneider, Jasper"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jasper_Schneider", "fargo", "PER", "Jasper Schneider"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jasper_Schneider", "fargo", "PER", "Jasper_Schneider"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeff_Severson", "fargo", "PER", "Jeffrey Kent Severson"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeff_Severson", "fargo", "PER", "Jeff Severson"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeff_Severson", "fargo", "PER", "Jeff_Severson"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeff_Severson", "fargo", "PER", "Severson, Jeff"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jennifer_Baumgardner", "fargo", "PER", "Jennifer_Baumgardner"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jennifer_Baumgardner", "fargo", "PER", "Jennifer Baumgardner"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jennifer_Baumgardner", "fargo", "PER", "Baumgardner, Jennifer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jim_Poolman", "fargo", "PER", "Poolman, Jim"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jim_Poolman", "fargo", "PER", "Jim Poolman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jim_Poolman", "fargo", "PER", "Jim_Poolman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/John_H._Lang", "fargo", "PER", "John H. Lang"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/John_H._Lang", "fargo", "PER", "John_H._Lang"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joshua_Boschee", "fargo", "PER", "Boschee, Josh"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joshua_Boschee", "fargo", "PER", "Joshua Boschee"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joshua_Boschee", "fargo", "PER", "Boschee, Joshua"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joshua_Boschee", "fargo", "PER", "Joshua_Boschee"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joshua_Boschee", "fargo", "PER", "Josh Boschee"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ken_Fowler", "fargo", "PER", "Ken Fowler"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ken_Fowler", "fargo", "PER", "Ken_Fowler"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ken_Fowler", "fargo", "PER", "Fowler, Ken"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Keri_Hehn", "fargo", "PER", "Keri Hehn"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Keri_Hehn", "fargo", "PER", "Hehn, Keri"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Keri_Hehn", "fargo", "PER", "Keri_Hehn"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Olaus_Murie", "fargo", "PER", "Murie, Olaus"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Olaus_Murie", "fargo", "PER", "Olaus_Murie"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Olaus_Murie", "fargo", "PER", "Olaus Johan Murie"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Olaus_Murie", "fargo", "PER", "Olaus Murie"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Paul_Johnsgard", "fargo", "PER", "Johnsgard, Paul"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Paul_Johnsgard", "fargo", "PER", "Paul Austin Johnsgard"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Paul_Johnsgard", "fargo", "PER", "Paul_Johnsgard"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Paul_Johnsgard", "fargo", "PER", "Paul Johnsgard"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Paul_Marquart", "fargo", "PER", "Paul_Marquart"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Paul_Marquart", "fargo", "PER", "Marquart, Paul"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Paul_Marquart", "fargo", "PER", "Paul Marquart"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Richard_Edlund", "fargo", "PER", "Richard Edlund"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Richard_Edlund", "fargo", "PER", "Richard_Edlund"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Richard_Edlund", "fargo", "PER", "Edlund, Richard"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Richard_W._Goldberg", "fargo", "PER", "Richard W. Goldberg"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Richard_W._Goldberg", "fargo", "PER", "Richard_W._Goldberg"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Susan_Krieg", "fargo", "PER", "Susan Krieg"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Susan_Krieg", "fargo", "PER", "Krieg, Susan"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Susan_Krieg", "fargo", "PER", "Susan_Krieg"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_P._Gerberding", "fargo", "PER", "Gerberding, William"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_P._Gerberding", "fargo", "PER", "William_P._Gerberding"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_P._Gerberding", "fargo", "PER", "William Gerberding"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_P._Gerberding", "fargo", "PER", "William P. Gerberding"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Anaïs Croze"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Ana%C3%AFs_Croze"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Croze, Ana�s"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Croze, Anais"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Croze, Anaïs"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Ana�s Croz"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "croze, Ana�s"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Anaïs"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Ana�s_Croze"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Croze, Ana%C3%AFs"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "croze, Anais"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Ana�s Croze"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Croz, Ana�s"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Anais croze"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Ana%C3%AFs Croze"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Ana�s croze"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ana%C3%AFs_Croze", "french", "PER", "Anais Croze"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Gwena%C3%ABlle Aubry"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Gwenaëlle Aubry"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Gwenaelle Aubry"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Gwena%C3%ABlle_Aubry"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Aubry, Gwena%C3%ABlle"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Gwena�lle_Aubry"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Gwena�lle Aubry"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Aubry, Gwenaelle"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Aubry, Gwenaëlle"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Gwena%C3%ABlle_Aubry", "french", "PER", "Aubry, Gwena�lle"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Sch%C3%B6ffer, Nicolas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Schoeffer, Nicolas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Nicolas Schöffer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Sch�ffer, Nicolas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Nicolas Schoffer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Nicolas Sch%C3%B6ffer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Nicolas_Sch%C3%B6ffer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Nicolas Schoeffer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Nicolas Sch�ffer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Nicolas_Sch�ffer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Schöffer, Nicolas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nicolas_Sch%C3%B6ffer", "french", "PER", "Schoffer, Nicolas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Th�o Mercier"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Th%C3%A9o_Mercier"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Théo Mercier"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Mercier, Th%C3%A9o"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Th�o_Mercier"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Mercier, Theo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Th%C3%A9o Mercier"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Mercier, Théo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Mercier, Th�o"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Th%C3%A9o_Mercier", "french", "PER", "Theo Mercier"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Chiara_Nappi", "hep", "PER", "Chiara_Nappi"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Chiara_Nappi", "hep", "PER", "Chiara R. Nappi"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Chiara_Nappi", "hep", "PER", "nappi, Chiara"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Chiara_Nappi", "hep", "PER", "Chiara nappi"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Chiara_Nappi", "hep", "PER", "Nappi, Chiara"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Chiara_Nappi", "hep", "PER", "Chiara Nappi"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Eva_Silverstein", "hep", "PER", "Eva_Silverstein"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Eva_Silverstein", "hep", "PER", "Eva Silverstein"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Eva_Silverstein", "hep", "PER", "Silverstein, Eva"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Matt_Witten", "hep", "PER", "Matt_Witten"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Matt_Witten", "hep", "PER", "Witten, Matt"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Matt_Witten", "hep", "PER", "Matthew Witten"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Matt_Witten", "hep", "PER", "Matt Witten"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Matt_Witten", "hep", "PER", "Witten, Matthew"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Shamit_Kachru", "hep", "PER", "Shamit_Kachru"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Shamit_Kachru", "hep", "PER", "Shamit Kachru"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Shamit_Kachru", "hep", "PER", "Kachru, Shamit"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Angelo_Savoldi", "hoboken", "PER", "Savoldi, Angelo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Angelo_Savoldi", "hoboken", "PER", "Angelo Savoldi"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Angelo_Savoldi", "hoboken", "PER", "Angelo_Savoldi"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bernard_Kenny", "hoboken", "PER", "Kenny, Bernard"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bernard_Kenny", "hoboken", "PER", "Bernard Kenny"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bernard_Kenny", "hoboken", "PER", "Bernard F. Kenny, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bernard_Kenny", "hoboken", "PER", "Bernard F. Kenny"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bernard_Kenny", "hoboken", "PER", "Bernard_Kenny"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bernard_Kenny", "hoboken", "PER", "Bernard Kenny, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bob_Bert", "hoboken", "PER", "Bertelli, Robert"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bob_Bert", "hoboken", "PER", "Bob Bert"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bob_Bert", "hoboken", "PER", "Harshing My Mellow"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bob_Bert", "hoboken", "PER", "Bob_Bert"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bob_Bert", "hoboken", "PER", "Robert Bertelli"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bob_Bert", "hoboken", "PER", "Bewitched (American band)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bob_Bert", "hoboken", "PER", "Harshing My Mellow (album)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bob_Bert", "hoboken", "PER", "Bert, Bob"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bob_Bert", "hoboken", "PER", "Bewitched"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carl_Chang_(tennis)", "hoboken", "PER", "Carl_Chang_(tennis)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carl_Chang_(tennis)", "hoboken", "PER", "Carl_Chang_"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carl_Chang_(tennis)", "hoboken", "PER", "Carl Chang (tennis)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carl_Chang_(tennis)", "hoboken", "PER", "Chang, Carl"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carl_Chang_(tennis)", "hoboken", "PER", "Carl Chang"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carl_Chang_(tennis)", "hoboken", "PER", "Carl Chang (tennis player)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carla_Katz", "hoboken", "PER", "Katz, Carla"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carla_Katz", "hoboken", "PER", "Carla_Katz"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carla_Katz", "hoboken", "PER", "Carla Katz"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Carla_Katz", "hoboken", "PER", "Carla A. Katz"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Derrick_Alston", "hoboken", "PER", "Derrick Samuel Alston"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Derrick_Alston", "hoboken", "PER", "Derrick Alston"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Derrick_Alston", "hoboken", "PER", "Derrick_Alston"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Derrick_Alston", "hoboken", "PER", "Alston, Derrick"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Frank_Winters", "hoboken", "PER", "Frank Mitchell Winters"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Frank_Winters", "hoboken", "PER", "Frank_Winters"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Frank_Winters", "hoboken", "PER", "Frank Winters"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Frank_Winters", "hoboken", "PER", "Winters, Frank"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Henry_Gutierrez", "hoboken", "PER", "Hendrig Gutierrez"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Henry_Gutierrez", "hoboken", "PER", "Gutierrez, Henry"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Henry_Gutierrez", "hoboken", "PER", "Henry Gutierrez"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Henry_Gutierrez", "hoboken", "PER", "Hendrig \"Henry\" Gutierrez"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Henry_Gutierrez", "hoboken", "PER", "Henry_Gutierrez"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Henry_Gutierrez", "hoboken", "PER", "Gutierrez, Hendrig"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jack_Lazorko", "hoboken", "PER", "Lazorko, Jack"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jack_Lazorko", "hoboken", "PER", "Jack Thomas Lazorko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jack_Lazorko", "hoboken", "PER", "Jack Lazorko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jack_Lazorko", "hoboken", "PER", "Jack_Lazorko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeff_Tamarkin", "hoboken", "PER", "Jeff Tamarkin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeff_Tamarkin", "hoboken", "PER", "Jeff_Tamarkin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeff_Tamarkin", "hoboken", "PER", "Tamarkin, Jeff"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joanne_Borgella", "hoboken", "PER", "Borgella, Joanne"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joanne_Borgella", "hoboken", "PER", "Joanne_Borgella"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joanne_Borgella", "hoboken", "PER", "Joanne Borgella"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ken_Freedman", "hoboken", "PER", "freedman, Ken"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ken_Freedman", "hoboken", "PER", "Ken_Freedman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ken_Freedman", "hoboken", "PER", "Freedman, Ken"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ken_Freedman", "hoboken", "PER", "Ken Freedman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ken_Freedman", "hoboken", "PER", "Ken freedman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Klaus_Grutzka", "hoboken", "PER", "Grutzka, Klaus"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Klaus_Grutzka", "hoboken", "PER", "Klaus_Grutzka"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Klaus_Grutzka", "hoboken", "PER", "Klaus Grutzka"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mark_SaFranko", "hoboken", "PER", "SaFranko, Mark"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mark_SaFranko", "hoboken", "PER", "Mark_SaFranko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mark_SaFranko", "hoboken", "PER", "Mark SaFranko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mark_SaFranko", "hoboken", "PER", "Mark_Sa Franko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mark_SaFranko", "hoboken", "PER", "Franko, Mark_Sa"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Maurice_Fitzgibbons", "hoboken", "PER", "Maurice Fitzgibbons"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Maurice_Fitzgibbons", "hoboken", "PER", "Maurice_Fitzgibbons"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Maurice_Fitzgibbons", "hoboken", "PER", "Fitzgibbons, Maurice"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Pat_Dapuzzo", "hoboken", "PER", "Dapuzzo, Pat"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Pat_Dapuzzo", "hoboken", "PER", "Pat Dapuzzo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Pat_Dapuzzo", "hoboken", "PER", "Pat_Dapuzzo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruben_J._Ramos", "hoboken", "PER", "Ruben J. Ramos, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruben_J._Ramos", "hoboken", "PER", "Ruben J. Ramos"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruben_J._Ramos", "hoboken", "PER", "Ruben_J._Ramos"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Tilo_Rivas", "hoboken", "PER", "Tilo Rivas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Tilo_Rivas", "hoboken", "PER", "Tilo_Rivas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Tilo_Rivas", "hoboken", "PER", "Rivas, Tilo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Tilo_Rivas", "hoboken", "PER", "Tilo E. Rivas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Miller_(writer)", "hoboken", "PER", "William_H._Miller_(writer)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Miller_(writer)", "hoboken", "PER", "William H. Miller (writer)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Miller_(writer)", "hoboken", "PER", "Mr. Ocean Liner"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Miller_(writer)", "hoboken", "PER", "William H. Miller"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Miller_(writer)", "hoboken", "PER", "William_H._Miller_"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Aharon_Barak", "kba2012", "PER", "Aharon Brick"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Aharon_Barak", "kba2012", "PER", "Barak, Aharon"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Aharon_Barak", "kba2012", "PER", "Barak, Aaron"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Aharon_Barak", "kba2012", "PER", "Brick, Aharon"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Aharon_Barak", "kba2012", "PER", "Aaron Barak"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Aharon_Barak", "kba2012", "PER", "Aharon Barak"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Aharon_Barak", "kba2012", "PER", "Aharon_Barak"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Alex_Kapranos"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Alex Huntley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Huntley, Alex"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Alexander Kapranos"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Krapranos, Alex"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Kapranas, Alex"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Alexander Paul Kapranos Huntley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Alex Kapranos"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Alex Kapranas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Kapranos, Alex"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Alex Krapranos"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alex_Kapranos", "kba2012", "PER", "Kapranos, Alexander"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alexander_McCall_Smith", "kba2012", "PER", "Alexander Mc Coll Smith"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alexander_McCall_Smith", "kba2012", "PER", "Alexander_Mc Call_Smith"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alexander_McCall_Smith", "kba2012", "PER", "Alexander McCall Smith"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alexander_McCall_Smith", "kba2012", "PER", "The 44 Scotland Street Series"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alexander_McCall_Smith", "kba2012", "PER", "Alexander McColl Smith"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alexander_McCall_Smith", "kba2012", "PER", "Alexander mccall smith"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alexander_McCall_Smith", "kba2012", "PER", "Alexander_McCall_Smith"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Alexander_McCall_Smith", "kba2012", "PER", "Call_Smith, Alexander_Mc"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Annie_Laurie_Gaylor", "kba2012", "PER", "Annie Laurie Gaylor"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Annie_Laurie_Gaylor", "kba2012", "PER", "Annie_Laurie_Gaylor"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bill_Coen", "kba2012", "PER", "Coen, Bill"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bill_Coen", "kba2012", "PER", "Bill_Coen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Bill_Coen", "kba2012", "PER", "Bill Coen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Boris_Berezovsky_"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Boris Berezovsky (businessman)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Boris Berezhovsky"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Death of Boris Berezovsky"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Boris Abramovich Berezovsky"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Boris_Berezovsky_(businessman)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Berezhovsky, Boris"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Boris Berezovsky"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Platon Elenin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Boris A. Berezovsky"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(businessman)", "kba2012", "PER", "Elenin, Platon"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(pianist)", "kba2012", "PER", "Boris Vadimovich Berezovsky"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(pianist)", "kba2012", "PER", "Boris_Berezovsky_"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(pianist)", "kba2012", "PER", "Boris_Berezovsky_(pianist)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(pianist)", "kba2012", "PER", "Boris Berezovsky (violinist)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(pianist)", "kba2012", "PER", "Boris Berezovsky (pianist)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Boris_Berezovsky_(pianist)", "kba2012", "PER", "Boris Berezovsky"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Charlie_Savage", "kba2012", "PER", "Charlie savage"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Charlie_Savage", "kba2012", "PER", "savage, Charlie"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Charlie_Savage", "kba2012", "PER", "Savage, Charlie"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Charlie_Savage", "kba2012", "PER", "Charlie_Savage"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Charlie_Savage", "kba2012", "PER", "Charlie Savage"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Darren_Rowse", "kba2012", "PER", "Pro Blogger"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Darren_Rowse", "kba2012", "PER", "ProBlogger"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Darren_Rowse", "kba2012", "PER", "Darren_Rowse"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Darren_Rowse", "kba2012", "PER", "Blogger.com, Pro"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Darren_Rowse", "kba2012", "PER", "Pro Blogger.com"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Darren_Rowse", "kba2012", "PER", "ProBlogger.com"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Darren_Rowse", "kba2012", "PER", "Darren Rowse"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Darren_Rowse", "kba2012", "PER", "Rowse, Darren"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Darren_Rowse", "kba2012", "PER", "Blogger, Pro"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Douglas_Carswell", "kba2012", "PER", "Carswell, Douglas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Douglas_Carswell", "kba2012", "PER", "Douglas Carswell"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Douglas_Carswell", "kba2012", "PER", "Douglas_Carswell"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Douglas_Carswell", "kba2012", "PER", "John Douglas Wilson Carswell"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Frederick_M._Lawrence", "kba2012", "PER", "Frederick_M._Lawrence"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Frederick_M._Lawrence", "kba2012", "PER", "Frederick M. Lawrence"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ikuhisa_Minowa", "kba2012", "PER", "Ikuhisa Minowa"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ikuhisa_Minowa", "kba2012", "PER", "Ikuhisa"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ikuhisa_Minowa", "kba2012", "PER", "Ikuhisa_Minowa"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ikuhisa_Minowa", "kba2012", "PER", "Minowa, Ikuhisa"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ikuhisa_Minowa", "kba2012", "PER", "Minowaman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/James_McCartney", "kba2012", "PER", "James Louis McCartney"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/James_McCartney", "kba2012", "PER", "James Louis Mc Cartney"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/James_McCartney", "kba2012", "PER", "James_Mc Cartney"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/James_McCartney", "kba2012", "PER", "James mccartney"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/James_McCartney", "kba2012", "PER", "James McCartney"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/James_McCartney", "kba2012", "PER", "Cartney, James_Mc"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/James_McCartney", "kba2012", "PER", "James_McCartney"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/James_McCartney", "kba2012", "PER", "McCartney, James"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/James_McCartney", "kba2012", "PER", "mccartney, James"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jim_Steyer", "kba2012", "PER", "Jim_Steyer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jim_Steyer", "kba2012", "PER", "Jim Steyer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jim_Steyer", "kba2012", "PER", "James P. Steyer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jim_Steyer", "kba2012", "PER", "James  P. Steyer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jim_Steyer", "kba2012", "PER", "Steyer, Jim"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jim_Steyer", "kba2012", "PER", "James (Jim) P. Steyer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lisa_Bloom", "kba2012", "PER", "Lisa_Bloom"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lisa_Bloom", "kba2012", "PER", "Bloom, Lisa"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lisa_Bloom", "kba2012", "PER", "Lisa Bloom"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lovebug_Starski", "kba2012", "PER", "Smith, Kevin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lovebug_Starski", "kba2012", "PER", "Starsky, Lovebug"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lovebug_Starski", "kba2012", "PER", "Starski, Lovebug"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lovebug_Starski", "kba2012", "PER", "Lovebug_Starski"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lovebug_Starski", "kba2012", "PER", "Kevin Smith"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lovebug_Starski", "kba2012", "PER", "Lovebug Starski"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lovebug_Starski", "kba2012", "PER", "Love Bug Starsky"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lovebug_Starski", "kba2012", "PER", "Lovebug Starsky"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lovebug_Starski", "kba2012", "PER", "Love Bug Starski"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mario_Garnero", "kba2012", "PER", "Garnero, Mario"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mario_Garnero", "kba2012", "PER", "Mario_Garnero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mario_Garnero", "kba2012", "PER", "Garnero, Mário"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mario_Garnero", "kba2012", "PER", "Mario Garnero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Mario_Garnero", "kba2012", "PER", "Mário Garnero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Emoto, Masoru"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Dr. Masaru Emoto"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Masaru_Emoto"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Water experiment"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Masaru Emoto"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "experiment, Water"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Masoru Emoto"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Emoto, Doctor"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Emoto, Masaru"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Emoto, Dr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Dr. Emoto"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Doctor masaru emoto"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Masaru_Emoto", "kba2012", "PER", "Doctor Emoto"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nasim Taleb"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nassim Nicholas Taleb"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nessim"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Tulip, Nero"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "taleb, Nassim"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Anti-fragility"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Taleb, Nicholas"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nissim"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nassim taleb"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nero Tulip"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nassim Taleb"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nassim_Nicholas_Taleb"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Taleb, Nassim"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Taleb, Nasim"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nicholas Nassim Taleb"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nassim nicholas taleb"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Antifragility"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Nassim_Nicholas_Taleb", "kba2012", "PER", "Nicholas Taleb"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Rodrigo_Pimentel", "kba2012", "PER", "Pimentel, Rodrigo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Rodrigo_Pimentel", "kba2012", "PER", "Rodrigo Pimentel"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Rodrigo_Pimentel", "kba2012", "PER", "Rodrigo_Pimentel"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Roustam_Tariko", "kba2012", "PER", "Rustam Tariko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Roustam_Tariko", "kba2012", "PER", "Tariko, Roustam"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Roustam_Tariko", "kba2012", "PER", "Tariko, Rustam"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Roustam_Tariko", "kba2012", "PER", "Roustam_Tariko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Roustam_Tariko", "kba2012", "PER", "Roustam Tariko"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Rendell, Ruth"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Baroness Rendell"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Vine, Barbara"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Baroness Rendell of Babergh"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Ruth Barbara Rendell, Baroness Rendell of Babergh"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Rendell, Lady"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Lady Rendell"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Ruth_Rendell"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Ruth rendall"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Rendell, Baroness"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Ruth Rendell"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Barbara Vine"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "The Reason Why: An Anthology of the Murderous Mind"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "rendall, Ruth"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Ruth Barbara Rendell"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Ruth_Rendell", "kba2012", "PER", "Ruth Rendell, Baroness Rendell of Babergh"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Satoshi_Ishii", "kba2012", "PER", "Satoshi Ishii"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Satoshi_Ishii", "kba2012", "PER", "Satoshi_Ishii"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Satoshi_Ishii", "kba2012", "PER", "Ishii, Satoshi"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Vladimir_Potanin", "kba2012", "PER", "Vladimir Olegovich Potanin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Vladimir_Potanin", "kba2012", "PER", "Potanin, Vladimir"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Vladimir_Potanin", "kba2012", "PER", "Vladimir_Potanin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Vladimir_Potanin", "kba2012", "PER", "Vladimir Potanin"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "William_Cohen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "Cohen, William Sebastian"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "Cohen, Bill"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "Cohen, Sebastian"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "William S. Cohen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "Cohen, William"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "William s cohen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "William Cohen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "Sebastian Cohen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "William Sebastian Cohen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_Cohen", "kba2012", "PER", "Bill Cohen"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_D._Cohan", "kba2012", "PER", "William D. Cohan,"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_D._Cohan", "kba2012", "PER", "William Cohan"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_D._Cohan", "kba2012", "PER", "William_D._Cohan"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_D._Cohan", "kba2012", "PER", "William D. Cohan"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_D._Cohan", "kba2012", "PER", "William, Cohan,"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_D._Cohan", "kba2012", "PER", "Cohan, William"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Gates,_Sr", "kba2012", "PER", "William Henry Gates&#160;II"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Gates,_Sr", "kba2012", "PER", "William_H._Gates,_Sr"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/William_H._Gates,_Sr", "kba2012", "PER", "William Henry Gates, Sr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth Hood \"Buddy\" MacKay, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "MacKay, Buddy"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Buddy Mackay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Buddy MacKay, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Buddy Mac Kay, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "MacKay, Kenneth"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth Mac Kay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Buddy Mackay, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "McKay, Buddy"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth Hood Mac Kay, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth Hood Mac Kay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Mackay, Buddy"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth H. Mac Kay, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Buddy_Mac Kay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kay, Buddy_Mac"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth Hood \"Buddy\" Mac Kay, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth MacKay, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth Mac Kay, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth Hood MacKay, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Buddy Mc Kay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth H. MacKay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth MacKay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth H. MacKay, Jr."),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Buddy MacKay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Buddy McKay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth H. Mac Kay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Buddy_MacKay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Buddy_MacKay", "ocala", "PER", "Kenneth Hood MacKay"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Chuck_Pankow", "ocala", "PER", "Pankow, Chuck"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Chuck_Pankow", "ocala", "PER", "Chuck Pankow"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Chuck_Pankow", "ocala", "PER", "Chuck_Pankow"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Haven_Denney", "ocala", "PER", "Haven_Denney"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Haven_Denney", "ocala", "PER", "Denney, Haven"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Haven_Denney", "ocala", "PER", "Haven Denney"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeremy_McKinnon", "ocala", "PER", "McKinnon, Jeremy"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeremy_McKinnon", "ocala", "PER", "Jeremy Wade McKinnon"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeremy_McKinnon", "ocala", "PER", "Jeremy McKinnon"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeremy_McKinnon", "ocala", "PER", "Kinnon, Jeremy_Mc"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeremy_McKinnon", "ocala", "PER", "Jeremy_Mc Kinnon"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Jeremy_McKinnon", "ocala", "PER", "Jeremy_McKinnon"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joey_Mantia", "ocala", "PER", "Mantia, Joey"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joey_Mantia", "ocala", "PER", "Joey_Mantia"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joey_Mantia", "ocala", "PER", "Joey Mantia"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Judd_Davis", "ocala", "PER", "Davis, Judd"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Judd_Davis", "ocala", "PER", "Judd Davis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Judd_Davis", "ocala", "PER", "Judd davis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Judd_Davis", "ocala", "PER", "Judd_Davis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Judd_Davis", "ocala", "PER", "davis, Judd"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Judd_Davis", "ocala", "PER", "Judd Dillon Davis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lorenzo_Williams_(basketball)", "ocala", "PER", "Williams, Lorenzo"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lorenzo_Williams_(basketball)", "ocala", "PER", "Lorenzo Williams"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lorenzo_Williams_(basketball)", "ocala", "PER", "Lorenzo_Williams_"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lorenzo_Williams_(basketball)", "ocala", "PER", "Lorenzo Williams (basketball)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Lorenzo_Williams_(basketball)", "ocala", "PER", "Lorenzo_Williams_(basketball)"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Randy_Ewers", "ocala", "PER", "Randy_Ewers"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Randy_Ewers", "ocala", "PER", "Ewers, Randy"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Randy_Ewers", "ocala", "PER", "Randy Ewers"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Reid_Nichols", "ocala", "PER", "Nichols, Reid"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Reid_Nichols", "ocala", "PER", "Reid_Nichols"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Reid_Nichols", "ocala", "PER", "Thomas Reid Nichols"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Reid_Nichols", "ocala", "PER", "Reid Nichols"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scot_Brantley", "ocala", "PER", "Scot Eugene Brantley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scot_Brantley", "ocala", "PER", "Scot_Brantley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scot_Brantley", "ocala", "PER", "Scot Brantley"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Scot_Brantley", "ocala", "PER", "Brantley, Scot"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Sean_Hampton", "ocala", "PER", "Hampton, Sean"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Sean_Hampton", "ocala", "PER", "Sean Hampton"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Sean_Hampton", "ocala", "PER", "Sean_Hampton"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Travis_Mays", "ocala", "PER", "Travis Cortez Mays"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Travis_Mays", "ocala", "PER", "Travis Mays"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Travis_Mays", "ocala", "PER", "Travis_Mays"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Travis_Mays", "ocala", "PER", "Mays, Travis"),
    streamcorpus::found_entity("https://twitter.com/BartowMcDonald", "ocala", "PER", "bartowmcdonald.com"),
    streamcorpus::found_entity("https://twitter.com/BartowMcDonald", "ocala", "PER", "Ocala Commercial Real Estate"),
    streamcorpus::found_entity("https://twitter.com/BartowMcDonald", "ocala", "PER", "Bartow McDonald"),
    streamcorpus::found_entity("https://twitter.com/BartowMcDonald", "ocala", "PER", "Bartow Mc Donald"),
    streamcorpus::found_entity("https://twitter.com/BartowMcDonald", "ocala", "PER", "Ocala Real Estate"),
    streamcorpus::found_entity("https://twitter.com/BartowMcDonald", "ocala", "PER", "McDonald, Bartow"),
    streamcorpus::found_entity("https://twitter.com/BartowMcDonald", "ocala", "PER", "BartowMcDonald"),
    streamcorpus::found_entity("https://twitter.com/KentGuinn4Mayor", "ocala", "PER", "Guinn4Mayor, Kent"),
    streamcorpus::found_entity("https://twitter.com/KentGuinn4Mayor", "ocala", "PER", "Guinn, Kent"),
    streamcorpus::found_entity("https://twitter.com/KentGuinn4Mayor", "ocala", "PER", "Kent Guinn4Mayor"),
    streamcorpus::found_entity("https://twitter.com/KentGuinn4Mayor", "ocala", "PER", "KentGuinn4Mayor"),
    streamcorpus::found_entity("https://twitter.com/KentGuinn4Mayor", "ocala", "PER", "Kent Guinn"),
    streamcorpus::found_entity("https://twitter.com/bobplaisted", "ocala", "PER", "bob plaisted"),
    streamcorpus::found_entity("https://twitter.com/bobplaisted", "ocala", "PER", "bobplaisted"),
    streamcorpus::found_entity("https://twitter.com/bobplaisted", "ocala", "PER", "RobertPlaisted"),
    streamcorpus::found_entity("https://twitter.com/bobplaisted", "ocala", "PER", "Robert Plaisted"),
    streamcorpus::found_entity("https://twitter.com/bobplaisted", "ocala", "PER", "Plaisted, Robert"),
    streamcorpus::found_entity("https://twitter.com/bobplaisted", "ocala", "PER", "Plaisted, Rob"),
    streamcorpus::found_entity("https://twitter.com/redmondmusic", "ocala", "PER", "Eric Redmond"),
    streamcorpus::found_entity("https://twitter.com/redmondmusic", "ocala", "PER", "Redmond, Eric"),
    streamcorpus::found_entity("https://twitter.com/redmondmusic", "ocala", "PER", "redmond music"),
    streamcorpus::found_entity("https://twitter.com/redmondmusic", "ocala", "PER", "redmondmusic"),
    streamcorpus::found_entity("https://twitter.com/sandrafriend", "ocala", "PER", "trail sand travel"),
    streamcorpus::found_entity("https://twitter.com/sandrafriend", "ocala", "PER", "trailsandtravel"),
    streamcorpus::found_entity("https://twitter.com/sandrafriend", "ocala", "PER", "sandrafriend"),
    streamcorpus::found_entity("https://twitter.com/sandrafriend", "ocala", "PER", "sandra friend"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joshua_Zetumer", "screenwriters", "PER", "Zetumer, Joshua"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joshua_Zetumer", "screenwriters", "PER", "Joshua_Zetumer"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Joshua_Zetumer", "screenwriters", "PER", "Joshua Zetumer"),
    streamcorpus::found_entity("https://twitter.com/MissMarcel", "screenwriters", "PER", "Marcel, Kelly"),
    streamcorpus::found_entity("https://twitter.com/MissMarcel", "screenwriters", "PER", "MissMarcel"),
    streamcorpus::found_entity("https://twitter.com/MissMarcel", "screenwriters", "PER", "Marcel, Miss"),
    streamcorpus::found_entity("https://twitter.com/MissMarcel", "screenwriters", "PER", "Miss Marcel"),
    streamcorpus::found_entity("https://twitter.com/MissMarcel", "screenwriters", "PER", "Kelly Marcel"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Barbara_Liskov", "turing", "PER", "Barbara Jane Liskov"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Barbara_Liskov", "turing", "PER", "Barbara Jane Huberman"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Barbara_Liskov", "turing", "PER", "Liskov, Barbara"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Barbara_Liskov", "turing", "PER", "Liskov"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Barbara_Liskov", "turing", "PER", "Barbara_Liskov"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Barbara_Liskov", "turing", "PER", "Barbara H. Liskov"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Barbara_Liskov", "turing", "PER", "Barbara Huberman Liskov"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Barbara_Liskov", "turing", "PER", "Barbara Liskov"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando_J._Corbat%C3%B3"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Corbato, Fernando"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando José \"Corby\" Corbató"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando Corbat�"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Corbat�'s law"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Corbat�, Fernando"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando Corbato"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando J. Corbato"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Corbato's law"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando_J._Corbat�"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "law, Corbato's"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando J. Corbat�"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "law, Corbat�'s"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Fernando_J._Corbat%C3%B3", "turing", "PER", "Fernando J. Corbat%C3%B3"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Juris_Hartmanis", "turing", "PER", "Juris_Hartmanis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Juris_Hartmanis", "turing", "PER", "Juris Hartmanis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Juris_Hartmanis", "turing", "PER", "Hartmanis"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Juris_Hartmanis", "turing", "PER", "Hartmanis, Juris"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Shafi_Goldwasser", "turing", "PER", "Shafrira Goldwasser"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Shafi_Goldwasser", "turing", "PER", "Shafi_Goldwasser"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Shafi_Goldwasser", "turing", "PER", "Goldwasser, Shafi"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Shafi_Goldwasser", "turing", "PER", "Goldwasser, Shafrira"),
    streamcorpus::found_entity("http://en.wikipedia.org/wiki/Shafi_Goldwasser", "turing", "PER", "Shafi Goldwasser")
  };

 }; // streamcorpus 

