/**
 * Autogenerated by Thrift Compiler (1.0.0-dev)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef streamcorpus_CONSTANTS_H
#define streamcorpus_CONSTANTS_H

#include "streamcorpus_types.h"

namespace streamcorpus {

class streamcorpusConstants {
 public:
  streamcorpusConstants();

};

extern const streamcorpusConstants g_streamcorpus_constants;

} // namespace

#endif
